name: Environment Setup Workflow

on:
  workflow_dispatch:
    inputs:
      port_context:
        description: "Port context in JSON format"
        required: true
      requires_s_3:
        description: "Does this workflow require S3?"
        required: true
      requires_ec_2:
        description: "Does this workflow require EC2?"
        required: true
      project:
        description: "Project name"
        required: true
      ttl:
        description: "Time to live (TTL) for the environment"
        required: true
      required_v_cluster:
        description: "Do we require vCluster"
        required: false
      prefix:
        description: "prefix"
        required: false
      EC2_Size:
        description: "EC2_Size"
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    - name: Print inputs
      run: |
        python .github/workflows/create_environment.py print_inputs \
          --port_context '${{ github.event.inputs.port_context }}' \
          --requires_s3 '${{ github.event.inputs.requires_s3 }}' \
          --requires_ec2 '${{ github.event.inputs.requires_ec2 }}' \
          --project '${{ github.event.inputs.project }}' \
          --ttl '${{ github.event.inputs.ttl }}' \
          --all '${{ github.event.inputs.ttl.port_context }}'

    - name: Create environment
      run: |
        python .github/workflows/create_environment.py create_environment \
          --project '${{ github.event.inputs.project }}' \
          --token "${{ env.PORT_TOKEN }}"

    
