name: Environment Setup Workflow

on:
  workflow_dispatch:
    inputs:
      port_context:
        description: "Port context in JSON format"
        required: true
      requires_s3:
        description: "Does this workflow require S3?"
        required: true
      requires_ec2:
        description: "Does this workflow require EC2?"
        required: true
      project:
        description: "Project name"
        required: true
      ttl:
        description: "Time to live (TTL) for the environment"
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Print inputs
      run: |
        python create_environment.py print_inputs \
          --port_context '${{ github.event.inputs.port_context }}' \
          --requires_s3 '${{ github.event.inputs.requires_s3 }}' \
          --requires_ec2 '${{ github.event.inputs.requires_ec2 }}' \
          --project '${{ github.event.inputs.project }}' \
          --ttl '${{ github.event.inputs.ttl }}'
          --all '${{ github.event }}'

    
