name: Environment Setup Workflow

on:
  workflow_dispatch:
    inputs:
      requires_s_3:
        description: "Does this workflow require S3?"
        required: true
      requires_ec_2:
        description: "Does this workflow require EC2?"
        required: true
      ttl:
        description: "Time to live (TTL) for the environment"
        required: true
      required_v_cluster:
        description: "Do we require vCluster"
        required: false
      prefix:
        description: "prefix"
        required: false
      EC2_Size:
        description: "EC2_Size"
        required: false
      triggered_by:
        description: "triggered_by"
        required: false
      runId:
        description: "runId"
        required: false
      project:
        description: "project"
        required: false
      project_id:
        description: "project_identifier"
        required: false
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    - name: Get token
      id: get_token
      run: |
        TOKEN=$(python .github/workflows/create_environment.py get_token \
          --client_id "${{ secrets.PORT_CLIENT_ID }}" \
          --client_secret "${{ secrets.PORT_CLIENT_SECRET }}")
        echo "PORT_TOKEN=$TOKEN" >> $GITHUB_ENV

    - name: Create environment
      run: |
        echo "----printing inputs-----"
        echo '${{ toJson(github.event.inputs) }}'
        echo "----printing context-----"
        echo '${{ github.event.inputs.triggered_by }}'
        echo "----printing context-----"
        python .github/workflows/create_environment.py create_environment \
          --project '${{ github.event.inputs.project_id }}' \
          --token '${{ env.PORT_TOKEN }}' \
          --ttl '${{ github.event.inputs.ttl }}' \
          --triggered_by '${{ github.event.inputs.triggered_by }}' \
    
